[package]
name = "sfs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
atty = "0.2"
clap = { version = "4.3", features = ["derive"] }
env_logger = { version = "0.10", default-features = false }
log = "0.4"
sfs-core = { path = "../core" }

[dev-dependencies]
trycmd = "0.14"
